native_libs/src/Core/Error.cpp
native_libs/src/Core/Error.h
native_libs/src/Core/Matrix2d.cpp
native_libs/src/Core/Matrix2d.h
native_libs/src/Core/Utils.cpp
native_libs/src/IO/csv.cpp
native_libs/src/IO/xlsx.cpp
src/Array2D.luna
src/Dataframes.luna
src/Main.luna
src/Utils.luna

This PR introduces unified mechanism for error handling on the boundary of C++/C/Luna. The goals are:
* to prevent crashes when Luna methods are called with invalid arguments;
* to provide better diagnostics to the user when something goes wrong;
* to unify way of reporting errors between various methods, so reporting/handling code can be easily reused — so having more robust code won't necessarily mean having to write more code.
Changes are twofold:
1. The C++ helper library C API functions all received a final parameter of type `const char **` for error reporting. On success, the `nullptr` is stored to the argument "pointee pointer". On failure, the "pointee pointer" is set to an error message.
* Error message memory is managed by the C++ library and is guaranteed to be kept at least …

Reworked C++/Luna error handling

---

native_libs/src/Analysis.cpp
native_libs/src/Analysis.h
native_libs/test/Tests.cpp

This PR corrects the RSI formula, fixing wrong results that resulted (but was not limited to) in #46.
Also, calculating RSI has been exposed from Analytics module, to allow for automatic tests for corner cases.
As written in #46:
> The behavior comes from the Python code given as implementation sample in #36. By comparing with [Wikipedia article](https://en.wikipedia.org/wiki/Relative_strength_index) it seems that samples with price decrease should count as 0 increase as well (and price increase should count as 0 decrease) for the purpose of mean increase calculation.
The Python code doesn't do that and samples consisting only of price growths yields nan instead of 100. I going to fix this, but this will change the behavior from specified.

Fix for #46 by changing the formula

---

native_libs/src/Core/ArrowUtilities.cpp
native_libs/src/Core/Common.h
native_libs/test/Tests.cpp

Previously passing such columns would create broken Table that could cause serious issues on attempted usage. With this change columns will be padded with nulls, so they all have the same length. Fixes #62.

Building Table from columns varying in length

---

native_libs/plotter/Matplotlib/Plot.cpp
native_libs/third-party/matplotlib-cpp/matplotlibcpp.h

This PR fixes how our bindings to matplotlib handle creation legend box with labels. Instead of blindly calling legend() when obtaining the final image and hope it makes sense, we call it when adding a plot with a label. This fixes two issues:
1) When we have multiple plots in a single image, each will have its own legend
2) When we have no labels, no legend box shall be created ( that fixes #51 ).
The screenshot below shows the fix: on the left the chart does not have an empty legend box, on the right we have two charts, each with their own legend box.

Fixing legend boxes in charts

---

native_libs/src/Core/Utils.cpp
native_libs/src/IO/Feather.cpp
native_libs/src/IO/Feather.h
native_libs/src/IO/IO.cpp
native_libs/src/IO/IO.h
native_libs/src/IO/XLSX.cpp
native_libs/src/IO/XLSX.h
native_libs/src/IO/csv.cpp
native_libs/src/IO/csv.h
native_libs/src/main.cpp
native_libs/test/Benchmarks.cpp
native_libs/test/Tests.cpp

The primary issue solved by this PR is #66 — allowing user to "just read" the file without specifying its format. The interface was already there, it just assumed always CSV. Now all the supported formats should be recognized: CSV, Apache Feather and XLSX. 
This PR also refactors the internal C++ interface of IO code. Support for CSV, Feather and XLSX were added separately, each with its own set of slightly differently named functions. This PR unifies them under a common interface, for easier usage, consistence and possible code reuse across all 3 format IO.
Ref #57
Fixes #66

Deducing file format when reading table + IO refactor

---

native_libs/third-party/matplotlib-cpp/matplotlibcpp.h

The actual issue was the "cmap" in the argument list — must have been left there by accident.
Also, updated arguments type and prevent them from being passed to Python when empty strings (I've adjusted Luna before to pass empty strings instead of null pointers).

Fix for #76

---

native_libs/src/Core/ArrowUtilities.cpp
native_libs/src/Core/ArrowUtilities.h
native_libs/src/main.cpp
src/Internal/CWrappers.luna

The function with padding was already done, by some mistake it wasn't properly connected to the Luna bindings.

Luna operations creating table from columns will adjust column length by padding with nulls

---

src/Table.luna

Fix division by zero when calling toJSON on an empty table. Fixes #64

---

.circleci/config.yml
appveyor.yml

As discussed earlier — there is no reason to hide our build artifacts.

Packages uploaded to S3 are publically readable

---

appveyor.yml
scripts/Main.hs
scripts/README.md

This removes v141 suffix from Dataframes package name. It was meant to denote the C++ toolset ABI, but:
1) we do not use any other toolset that we need to differentiate between
2) library offers C API and its consumer (like luna-studio packaging scripts) should not care what was used to build it
Also, fixing the uploaded artifact name that caused package not to appear on S3.

Unify package name

---

appveyor.yml

Unexpectedly for me, AppVeyor preserved a relative path from repository root when uploading the package to S3. With this, the artifact finally lands where it should.

Fixed AppVeyor's S3 upload path

---

src/Table.luna

Using just `Table` reports errors about non-exhaustive patterns in visualizer methods. This PR fixes that.

Fix toJSON and shortRep for table constructor

---

native_libs/src/Python/PythonInterpreter.cpp

When making code relocatable, an assumption was introduced that Dataframes will be linked with python library that looks like the one from a default local build. Using framework distribution of Python in this case causes crash. 
This PR ignores missing Python library, if there's a framework. 
Though in the long-term we should have some better way to discern between official package deployed environment and development environment.
@sylwiabr  -- please test if this change is enough to solve the issue

Don't crash on developer builds on mac 

---

native_libs/src/Python/PythonInterpreter.cpp

AppImage sets bogus paths for PYTHONHOME and PYTHONPATH variables. That breaks Python interpreter in developer builds, like described in #110. Packaged builds were unaffected, as we were overwriting these paths anyway (as we know exactly what the package structure is like and where to look for python).
This PR adds a workaround -- remove bogus variables and allow local Python installation figure things on its own.

Fix python environment when being run from AppImage. (#110)

---

native_libs/src/Core/Common.cpp
native_libs/src/Core/Common.h
native_libs/src/Processing.cpp
native_libs/src/Processing.h
native_libs/src/main.cpp
native_libs/test/Tests.cpp
src/Table.luna

The slice operation previously didn't check the bounds, leading to invalid objects being created, leading to a possible crashes (or other unexpected results). Issue affected buffers, arrays, columns. 
The issue also affected functions implemented on slice, like `take` or `drop` (reported as #63).

Bounds checking on slice operation

---

native_libs/src/Python/PythonInterpreter.cpp

The long paths in `vmmap` output are shortened by default. We require having full paths though, so we need to pass `-w` flag to allow wide output.

Fix for #117 — vmmap needs -w argument so long paths are not shortened.

---

scripts/Main.hs
scripts/Platform/OSX.hs

This PR fixes issue where some libraries we package refer to `libicudata.63.dylib` while the shipped binary is `libicudata.63.1.dylib`. 
The more detailed explanation is in the code. Basically if the name of library matches, the dependency will be rewritten to the actual file.

Fix issue with packaging ICU on macOS

---

src/Internal/CWrappers.luna

Another occurence of #106, same fix (cf #108).

rollingIntervalMultiple: fixed binary interface mismatch

---

src/Column.luna

Now that `slice` checks bounds, the `toJSON` shouldn't request more elements than there are available.
Otherwise attempts at visualization yield errors.

Fixed an issue with toJSON visualization after #116.

---

.circleci/config.yml

We cannot use brew anymore for this library, as the `apache-arrow` formula was removed: https://github.com/Homebrew/homebrew-core/commit/6cd7f61d2d07d5fd9f8747ea0f620169cc8a2434

[ci, mac] Building Apache Arrow from sources

---

appveyor.yml
native_libs/src/Analysis.cpp

Visual 15.9 has a regression. Because AppVeyor forces us to use that particular build, we need to have this workaround. To be removed when we upgrade to 16.0 or when forcing 15.8 toolset is possible.
See https://developercommunity.visualstudio.com/content/problem/395993/159-regression-error-on-valid-c-code-constexpr-if.html

Fix AppVeyor build

---

data/ungroupable.csv
native_libs/src/Core/ArrowUtilities.cpp
native_libs/src/Core/ArrowUtilities.h
native_libs/src/Processing.cpp
native_libs/src/Processing.h
native_libs/src/main.cpp
native_libs/test/Tests.cpp
src/Internal/CWrappers.luna
src/Main.luna
src/Table.luna

An utility needed for upcoming demo. Function `Table.ungroupSplittingOn` allows ungrouping rows by splitting strings in a given column.
E.g.
```
import Std.Base
import Std.Foreign.C.Value
import Dataframes.Column
import Dataframes.Types
import Dataframes.Table
def renameAt self index name:
col = Table.columnAt index
col2 = col.rename name
def main:
t = Table.read "C:/Users/mwu/Downloads/games.csv"
t2 = t.ungroupSplittingOn "tag" " "
print t
print t2
```
Basically, the purpose is to transform table like:
|col1|col2|
|---|------|
| a |  foo bar |
| b | foo baz  |
| c | fff      |
into:
|col1|col2|
|---|------|
| a |  foo |
| a | bar  |
| b | foo  |
| b | baz  |
| c | fff  |
It allows ungrouping rows by splitting over any string separator in given string column.
In a longer term this use …

Ungroup splitting

---

scripts/Main.hs
scripts/Platform/Linux.hs
scripts/Program/Patchelf.hs
scripts/package.yaml

This PR:
1. Moved `installBinary` and `installDependencyTo` from `Program.Patchelf` module to `Platform.Linux` module. Program modules are intended to contain simple wrappers over program commands. More complex actions involving calling multiple programs do not belong there.
2. `installBinary` temporarily changes patched binary file permissions to make it writeable. Even though this is a copy that we own it might be non-writable — this blocks Azure-based CI, as Docker containers are used with non-root user there (and installed libraries are read-only).

[packaging] Set binaries to be writeable during patching. 

---

.ci/azure-pipelines.yml

Does what it says on the tin. This is the same fix that we applied to Luna in https://github.com/luna/luna/pull/395 to prevent CI from running both percommit and in a PR context.

Update CI config to prevent double runs in PRs

---

src/Internal/CWrappers.luna

Recent fixes to the Luna typechecker surfaced an issue in this library. `Array.with` wrongly accepted `Ptr` where `Pointer` was declared. While it was fine on runtime, due to runtime API match, it was indeed an error. This PR fixes the issue.
`ManagedPointer` learned how to convert itself to a `Pointer` instead of a `Ptr`, and this is incorporated in this PR.
Please include the following checklist in your PR:

Fix pointer vs ptr type mismatch

---

src/Column.luna
src/Value.luna

Due to recent fixes in the typechecker, Column.toList method stopped to compile. See #61. 
This PR addresses the issue by introducing a new class `Dataframes.Value` that is meant to be a type-erased wrapper for any supported cell value. With such type, Column.toList can just return `[Value]` and properly typecheck.
Some `Column` methods that depended on `Column.toList` changed their return type to `Value`:
* minValue
* maxValue
* meanValue
* medianValue
* stdValue
* varValue
* sumValue
I don't think that involves any breakage.
Please include the following checklist in your PR:

Fix for Column.toList to properly compile on recent typechecker. See #61

---

native_libs/src/Python/PythonInterpreter.cpp

Since `time_of_day` is no longer a class in the new version of `date`, this line would break when compiling
Mentioned in #152

Fix PythonInterpreter.cpp for new version of date

---

native_libs/src/Core/Common.h
native_libs/src/IO/IO.cpp
native_libs/src/IO/IO.h
native_libs/test/Tests.cpp

It has been reported on Discord that our current error message on `Table.read` not being able top open/read file is not helpful. Reason is two-fold:
1) the error pretty printing call was missing an argument, so we got error-formetting-error instead of actual error;
2) the actual error wouldn't be helpful anyway -- we ignored the actual error with reading file (that can be caused by wrong permission settings or wrong path), because we expect failure possibility when trying to match proper parser for given file.
Now not being able to read file is a special class of errors that stop the parser-matching routine and allow to give proper diagnostics to the user.
Please include the following checklist in your PR:

Better error message on failed Table.read
